// Design Tokens Composable - Generated by Style Dictionary
export interface DesignTokens {
  // This file will be populated after running 'npm run tokens:build'
}

export const tokens: DesignTokens = {
  // This file will be populated after running 'npm run tokens:build'
};